import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/features/layout';
import './globals.css';
import configuration from '../configuration';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: configuration.APP_TITLE,
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="ko">
    <body className={inter.className}>
    <Header />
    {children}
    </body>
    </html>
  );
}







