import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classNames from 'classnames';
import configuration from '../configuration';
import { Header, Footer } from '@/features/layout';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: configuration.APP_TITLE,
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
      <body className={classNames(inter.className, 'min-w-screen min-h-screen flex flex-col')}>
        <Header />
        <main className="flex-1 w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
